### ISSUE TITLE
feature request: more flexible formatting of candidates in peruse

### ISSUE THREAD

**Issue by Hugo-Heagren** [Overdr0ne/gumshoe#11]
I've just discovered this package, and it's really great -- I've immediately switch from goto-change, which I used to use.

The only thing that isn't quite perfect is the formatting of candidates in calls to completing-read in the peruse commands. In particular, I prefer different elements to be vertically aligned, and separated by space (rather than by a | character).

Would you accept a PR making this configurable?

**Comment by Overdr0ne** [comment]
Oh yeah, I guess I had never customized those, good catch. I certainly would accept a PR if you have it handy. I could also add that in if you'd like. Really glad to hear the package is working out for you.

**Comment by Overdr0ne** [comment]
Hey, it's been a while since I've looked at this package, and realized I had a lot of unfinished features, so I rolled this feature in with all of those changes. There were some nasty bugs in the backtracking code that really needed fixing. Hopefully things are still backward compatible, but just let me know if things aren't working for you.
