### ISSUE TITLE
Add dired buffers easily?

### ISSUE THREAD

**Issue by michalrus** [Overdr0ne/gumshoe#14]
Hey! First of all, it’s a wonderful package, just what I needed! :bow: 

I have a question, is it easy to add `dired` buffers to history, too? Maybe we could have some way of providing our own buffer filter?

Thank you!

**Comment by Overdr0ne** [comment]
Hey michalrus, first, very sorry for such a late reply, I just had my notifications turned off and missed this.

Are you saying gumshoe is not tracking your position within dired buffers? It definitely should be. Though, if you would like to filter for only positions in dired buffers during backtracking or perusing, that is certainly possible. The way things work is, when you enable gumshoe, it tracks all of your positions, along with a bunch of metadata about each position, including the major mode. So sometime after gumshoe is enabled, in your config, first, you just need to create a predicate that says an entry's major-mode is equal to "dired-mode",
```
(cl-defmethod gumshoe--in-dired-buffer-p ((entry gumshoe--entry))
  "Check if ENTRY in a dired buffer."
  (equal (oref entry major-mode) "dired-mode"))
```
...then create the backtrack and peruse functions that use that predicate to filter. I've provided a convenience macro that creates both of these:
```
(gumshoe--make-xface gumshoe-dired-backtrack gumshoe-peruse-in-dired gumshoe--in-dired-buffer-p)
```
I would prefer to not add that specifically to the package, because that open the door to enumerating all possible different filters, which is basically infinite. But I will try to add a similar example to the readme.

Does that work for your use case?

**Comment by michalrus** [comment]
Hey @Overdr0ne, sorry for my late reply this time. And thank you for such a detailed answer and explanation! :bow: :heart_eyes: That does it :muscle:
